"""add journal_entry and profile journal settings

Revision ID: 18e1688678a2
Revises: 9728d7bc9d0f
Create Date: 2026-09-14 08:31:03.702888

Downgrade drops every journal entry; the prose is not recoverable.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18e1688678a2"
down_revision: Union[str, Sequence[str], None] = "9728d7bc9d0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("gratitude", sa.Text(), nullable=True),
        sa.Column("day_quality", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "entry_date", name="uq_journal_profile_date"),
    )
    op.create_index(
        op.f("ix_journal_entry_entry_date"),
        "journal_entry",
        ["entry_date"],
        unique=False,
    )
    op.create_index(op.f("ix_journal_entry_id"), "journal_entry", ["id"], unique=False)
    op.create_index(
        op.f("ix_journal_entry_profile_id"),
        "journal_entry",
        ["profile_id"],
        unique=False,
    )
    op.add_column(
        "profile",
        sa.Column(
            "journal_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column("profile", sa.Column("journal_prompt_time", sa.Time(), nullable=True))
    op.add_column("profile", sa.Column("journal_prompt", sa.Text(), nullable=True))
    op.add_column(
        "profile",
        sa.Column(
            "journal_gratitude_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "journal_gratitude_enabled")
    op.drop_column("profile", "journal_prompt")
    op.drop_column("profile", "journal_prompt_time")
    op.drop_column("profile", "journal_enabled")
    op.drop_index(op.f("ix_journal_entry_profile_id"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_id"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_entry_date"), table_name="journal_entry")
    op.drop_table("journal_entry")
    # ### end Alembic commands ###
