"""add countdown category

Revision ID: 423e71e7cfaf
Revises: 28c437ef804e
Create Date: 2026-08-04 16:02:13.733511

Add countdown_category and link countdowns to it.

Downgrade drops the table and the column, which loses every group colour. It
also cannot restore each countdown's original untrimmed `category` text: the
upgrade overwrites it with the trimmed value, and the untrimmed original is
stored nowhere.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "423e71e7cfaf"
down_revision: Union[str, Sequence[str], None] = "28c437ef804e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countdown_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "name", name="uix_countdown_category_profile_name"
        ),
    )
    op.create_index(
        op.f("ix_countdown_category_id"), "countdown_category", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_countdown_category_profile_id"),
        "countdown_category",
        ["profile_id"],
        unique=False,
    )
    op.add_column("countdown", sa.Column("category_id", sa.Integer(), nullable=True))
    # Named explicitly: the default "ix_<table>_<column>" pattern collides with
    # countdown_category's own id index (both compute to ix_countdown_category_id).
    op.create_index(
        "ix_countdown_category_id_fk", "countdown", ["category_id"], unique=False
    )
    op.create_foreign_key(
        "countdown_category_id_fkey",
        "countdown",
        "countdown_category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # One record per distinct trimmed name per profile, coloured with the first
    # non-null member colour by id.
    op.execute(
        """
        INSERT INTO countdown_category (profile_id, name, color, created_date)
        SELECT profile_id, name, color, NOW() FROM (
          SELECT profile_id, btrim(category) AS name, color,
                 row_number() OVER (PARTITION BY profile_id, btrim(category)
                                    ORDER BY (color IS NULL), id) AS rn
          FROM countdown
          WHERE category IS NOT NULL AND btrim(category) <> ''
        ) t WHERE rn = 1
        """
    )
    op.execute(
        """
        UPDATE countdown c SET category_id = cc.id, category = cc.name
        FROM countdown_category cc
        WHERE cc.profile_id = c.profile_id AND cc.name = btrim(c.category)
        """
    )
    # Whitespace-only categories get no record; the client already renders them
    # as "Other".
    op.execute(
        "UPDATE countdown SET category = NULL "
        "WHERE category IS NOT NULL AND btrim(category) = ''"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("countdown_category_id_fkey", "countdown", type_="foreignkey")
    op.drop_index("ix_countdown_category_id_fk", table_name="countdown")
    op.drop_column("countdown", "category_id")
    op.drop_index(
        op.f("ix_countdown_category_profile_id"), table_name="countdown_category"
    )
    op.drop_index(op.f("ix_countdown_category_id"), table_name="countdown_category")
    op.drop_table("countdown_category")
    # ### end Alembic commands ###
