"""add_sort_order_to_habit_table

Revision ID: 4a30fe0d63b9
Revises: 824920552c71
Create Date: 2025-12-09 14:36:20.209791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a30fe0d63b9"
down_revision: Union[str, Sequence[str], None] = "824920552c71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habit",
        sa.Column(
            "archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "habit",
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.create_index(op.f("ix_habit_sort_order"), "habit", ["sort_order"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_habit_sort_order"), table_name="habit")
    op.drop_column("habit", "sort_order")
    op.drop_column("habit", "archived")
    # ### end Alembic commands ###
