"""drop countdown category

Revision ID: 5508c9153583
Revises: acacbc9f1ee5
Create Date: 2026-08-06 11:42:32.074797

`category` mirrored the group's record name exactly, so downgrade rebuilds it
from `category_id`. A countdown with no group gets NULL, which is what it held.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5508c9153583"
down_revision: Union[str, Sequence[str], None] = "acacbc9f1ee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countdown", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column("countdown", sa.Column("category", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE countdown c SET category = cc.name
        FROM countdown_category cc
        WHERE cc.id = c.category_id
        """
    )
