"""habit reminder time and days

Revision ID: 75894aeded77
Revises: 2f964162ecc8
Create Date: 2026-09-23 14:54:45.010360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75894aeded77'
down_revision: Union[str, Sequence[str], None] = '2f964162ecc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('reminder_time', sa.Time(), nullable=True))
    op.add_column('habit', sa.Column('reminder_days', sa.Integer(), server_default='127', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'reminder_days')
    op.drop_column('habit', 'reminder_time')
    # ### end Alembic commands ###
