"""add is_admin field to user table

Revision ID: 824920552c71
Revises: 95973b1999f3
Create Date: 2025-11-01 17:20:49.014981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824920552c71'
down_revision: Union[str, Sequence[str], None] = '95973b1999f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first with a default value
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.false()))
    # Set existing rows to False
    op.execute("UPDATE \"user\" SET is_admin = FALSE WHERE is_admin IS NULL")
    # Make column NOT NULL
    op.alter_column('user', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
