"""add Countdown.archived_date

Revision ID: 9728d7bc9d0f
Revises: 36d838ea843f
Create Date: 2026-08-17 11:43:22.165456

Nullable, so every existing countdown starts live. Downgrade drops the column
and with it which countdowns had been archived.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9728d7bc9d0f"
down_revision: Union[str, Sequence[str], None] = "36d838ea843f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countdown", sa.Column("archived_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countdown", "archived_date")
    # ### end Alembic commands ###
