"""drop countdown color

Revision ID: acacbc9f1ee5
Revises: 423e71e7cfaf
Create Date: 2026-08-06 11:25:07.986305

A countdown's colour comes from its category record. Downgrade re-adds the
column empty: the per-countdown values cannot be restored.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acacbc9f1ee5"
down_revision: Union[str, Sequence[str], None] = "423e71e7cfaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countdown", "color")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countdown",
        sa.Column("color", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
